# Name of workflow
name: Cypress Component Tests

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      # Install dependencies
      - name: ðŸ§° Install Dependencies
        run: npm install

      - name: Debug MongoDB URI
        run: echo "MongoDB URI is $MONGODB_URI"

      # Build dist files
      - name: Build server and client
        run: npm run build

      # Run server before E2E test
      - name: Startup server
        run: npm run start & npx wait-on http://localhost:3001
        
      # Run Cypress
      - name: Run Cypress Component Test
        run: npm run test-component
      
      - name: Run Cypress E2E Test
        run: npm run test
